openapi: 3.2.0
info:
  version: 2.0.0
  title: Opal Search API
  license:
    name: Opal API License
    url: https://www.workwithopal.com/api-license
  description: "The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “NOT RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) [[RFC2119](https://tools.ietf.org/html/rfc2119)] [[RFC8174](https://tools.ietf.org/html/rfc8174)] when, and only when, they appear in all capitals, as shown here.\n\n# Other API Versions\n\nThe [v3 API](/api/documentation/v3) is less complete than the v2 API, and is still a work in progress. Currently, if a resource has endpoints in both the v2 API and the v3 API you **SHOULD** use the v2 API endpoints. At some point in the future we will recommend the v3 API instead.\n\n# Documentation Organization\n\nv2 API endpoints are categorized by stability:\n\n1. JSON:API\n2. Other\n3. Unstable\n4. Proposed\n\nv2 API endpoints in the “JSON:API”, “Unstable”, and “Proposed” categories are [JSON:API](https://jsonapi.org)-compliant ([specification](https://jsonapi.org/format/)) and can be used with any [JSON:API-compliant client](https://jsonapi.org/implementations/).\n\n<aside>\n\nTo strictly comply with the JSON:API specification your requests for endpoints in the “JSON:API”, “Unstable”, and “Proposed” categories **MUST** set the `Accept` HTTP header to `application/vnd.api+json`. The server response’s `Content-Type` HTTP header will also be `application/vnd.api+json`.\n\nYou **SHOULD** use `application/vnd.api+json` for maximum stability, but v2 API endpoints **MAY** allow the `Accept` HTTP header to be `application/json`; if so, the response’s `Content-Type` HTTP header will be `application/json`. This support for `application/json` **MAY** disappear from a given endpoint at any time, and is not available on all endpoints.\n</aside>\n\n“Other” endpoints are stable, but do not follow the JSON:API specification. (Some “Other” endpoints have data that resembles the JSON:API structure, but **MUST** be parsed as generic JSON.) Your requests **MUST** set the `Accept` HTTP header to `application/json`, and the response’s `Content-Type` HTTP header will be `application/json`.\n\n## Unstable Endpoints\n\n*Note:* This generally refers resources in the “Unstable” category, but includes endpoints with a summary that’s prefixed by `[UNSTABLE]`. These `[UNSTABLE]` endpoints may be part of a “Stable” resource.\n\nThe data structure and behavior of “Unstable” endpoints are not guaranteed, and we **MAY** change them at any time. You **MUST NOT** use these endpoints for production features, but **MAY** use them as a preview of upcoming features, and we welcome feedback.\n\n## Proposed Endpoints\n\n“Proposed” endpoints **MUST NOT** be used (they’re not yet implemented), and we **MAY** change or remove them at any time. We publish them at our discretion to share our plans and encourage internal feedback. We also welcome your feedback.\n\n# Design Principles\n\n## Breaking Changes\n\nWe **MAY** expand the data for “JSON:API” and “Other” resources, but will not change or remove existing attributes or relationships for these resources. These expansions should not require any changes to your code.\n\nWe provide no guarantees for “Unstable” and “Proposed” endpoints.\n\n## Firehose Rule\n\nBy default endpoints include all the relevant data that’s accessible to the authenticated user. Clients **MAY** specify filters, ordering, pagination, sparse fields, and other limiting mechanisms to pare down the desired data.\n\n*Note:* Existing endpoints **MAY NOT** follow this maximalist approach, but new endpoints will, and we **MAY** enhance existing endpoints.\n\n## Obscurity\n\nIn order to provide customers with as much privacy as possible, many API calls that fail authorization will return `404 Not Found` rather than `403 Forbidden`. Do not design frontends around the expectation that a `404 Not Found` status code means a resource would not be returned given different authentication credentials.\n\n# Authentication Strategies\n## OAuth 2.0\nOpal uses OAuth 2.0 (https://oauth.net/2) to authenticate users and grant access to protected resources. After registering your application as an OAuth client, you must get permission from each user before accessing their account.\n\nThe main steps are:\n\n1. Register your application\n2. Direct the user to Opal, to authorize your application\n3. Opal confirm's user identity, and asks the user to grant your application permissions\n4. Opal issues tokens your application can use to access the user's Opal resources\n5. Your application can begin making requests to the Opal API on behalf of the user\n\n### Roles\n#### Client\nThe 3rd-party application accessing the API on behalf of the User.\n\n#### API\nAPI endpoints used to interact with a User's resources in Opal.\n\n#### User\nThe person authorizing the Client to access to their Opal account.\n\n### Registering your application\nApplication registration is currently a manual process.\n\nTo begin, you will need to provide the following information to the Opal integrations team:\n\n- Application name\n- Logo URI\n- Redirect URI\n\nIn return, expect to receive:\n\n- Client ID\n  - public\n- Application secret\n  - keep this private\n  - keep this written down someplace safe. Opal cannot retrieve this for you if it is lost.\n\n### Authorization\nFor a Client to make API requests on behalf of Users, the User must first give consent.\nHere is an overview of the consent flow:\n\n1. Direct the User to grant access in Opal\n\n```\nhttps://login.ouropal.com/oauth2/auth?grant_type=authorization_code&scope=offline_access&response_type=code&client_id={client_id}&state={state}&redirect_uri={url_encoded_redirect}\n```\n\nParameters:\n- `client_id`: Provided by Opal.\n- `grant_type`: Set the value to authorization_code to receive a code string that can be exchanged for an access token.\n- `redirect_uri`: Defined by Client. After authentication, the user will be directed to this location.\n- `response_type`: The value code should be set for refresh tokens to be issued.\n- `scope`: The value offline_access must be present if you wish to use refresh tokens.\n- `state`: Defined by the Client. A unique value used to validate the response.\n\n\n2. If logged out, User is directed to log in to Opal\n\n3. User is redirected to consent page (if the User has not already given consent)\n\n```\nhttps://login.ouropal.com/oauth2/consent?consent_challenge=abc123\n```\n\n4. If the User grants permission, User is sent to the specified `redirect_uri`\n\n```\nhttps://example.com/defined-by-client?code=Mu9z2DndN7TfXSLaf99O8ReqqXqMabXhSqP5e0jlx_Q.naLKbko-GyfPJRGYcWyclxU0sBGwygPy05OSFww0XZ8&scope=offline_access&state={state}\n```\n\nParameters:\n- `code`: The Client may use this to get an access token.\n- `scope`: API permissions granted to the Client by the User.\n- `state`: The validation string provided by the Client in step 1.\n\nIf the User declines the consent prompt, User will be sent to the same `redirect_uri`, but with an error parameter :\n\n```\nhttps://example.com/defined-by-client?error=consent+request+denied&state={state}\n```\n\nParameters:\n- `error`: A brief description of the issue.\n- `state`: The validation string provided by the Client in step 1.\n\n### Retrieving Access Token\nYou must make a POST request to the token endpoint to get an access token, before the code expires:\n\n```\ncurl -X POST \\\n  https://login.ouropal.com/oauth2/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d 'code={code}&client_id={client_id}&redirect_uri={url_encoded_redirect}&client_secret={client_secret}&grant_type=authorization_code'\n```\n\nParameters:\n- `code`\n- `client_id`: Client ID provided by Opal.\n- `client_secret`: Client secret provided by Opal.\n- `grant_type`: Set value to authorization_code .\n- `redirect_uri`: Optional.\n\nIf successful, a JSON-formatted response body will contain the access_token and refresh_token:\n\n```json\n{\n  \"access_token\":\"ABC123\",\n  \"token_type\":\"bearer\",\n  \"expires_in\":3600,\n  \"refresh_token\":\"DEF456\",\n  \"scope\":\"offline_access\"\n}\n```\n\n### Refreshing an Access Token\nOnce the access_token expires, you may generate a new one at the same token endpoint, but with different parameters.\nNote that in this request, a \"refresh_token\" parameter is used instead of \"code\", and the \"grant_type\" value is now \"refresh_token\" instead of \"authorization_code\".\n\n```\ncurl -X POST \\\n  https://login.ouropal.com/oauth2/token \\\n  -H 'Content-Type: application/x-www-form-urlencoded' \\\n  -d 'refresh_token={refresh_token}&client_id={client_id}&redirect_uri={url_encoded_redirect}&client_secret={secret}&grant_type=refresh_token'\n```\n\nParameters:\n- `client_id`: Client ID provided by Opal.\n- `client_secret`: Client secret provided by Opal.\n- `grant_type`: Set value to refresh_token .\n- `redirect_uri`: Optional.\n- `refresh_token`: Refresh token value\n\n### Making Authenticated Requests\n\nSet an authorization header in your requests, specifying your access token as documented here: https://tools.ietf.org/html/rfc6750#section-2.1.\n\n**NOTE** that the `Authorization` header supercedes the `Session-Token` header described in the documentation for many endpoints. Specifying an `Authorization` header means you do not need to specify a `Session-Token` header.\n\n```\nAuthorization: Bearer ACCESS_TOKEN\n```\n\nFor example:\n```\n     GET /resource HTTP/1.1\n     Host: server.example.com\n     Authorization: Bearer mF_9.B5f-4.1JqM\n```\n\n### Client Revoke/Rolling OAuth secrets\nClient secrets must be kept secret and not exposed outside of the token retrieval requests. If a secret has been potentially compromised, please notify Opal as soon as possible and let us know the OAuth client id associated with the secret. We will roll/update the secret, which will invalidate all existing access and refresh tokens. Invalidating tokens will cause users to need to reauthenticate, but consent should be remembered.\n"
servers:
- url: https://login.ouropal.com
tags:
- name: Search
paths:
  /api/v1/search:
    get:
      tags:
      - Search
      operationId: ReadSearchesV1
      summary: Returns all entities that match query string filtered by brand slug
      security:
      - oauth2:
        - offline_access
      - api_key:
        - Session-Token
      description: Provides an elasticsearch query against `JumpSearchIndexV1#display_name`
      parameters:
      - name: slug
        in: query
        required: true
        description: The workspace to filter for
        schema:
          type: string
      - name: query
        in: query
        required: true
        description: The search string to query against
        schema:
          type: string
      responses:
        '200':
          description: An array of search results
          content:
            application/json:
              x-not-json-api: true
              schema:
                type: object
                title: Collection of search results
                required:
                - data
                properties:
                  data:
                    type: array
                    items:
                      title: search
                      type: object
                      required:
                      - type
                      - brand_ids
                      - display_name
                      - document_version
                      - id
                      - index_updated_at
                      - is_private
                      - is_visible
                      - navigation_path
                      - preview_url
                      - asset_reference_asset_type
                      - asset_reference_created_at
                      - asset_reference_full_url
                      - asset_reference_user_name
                      - board_created_at
                      - board_created_by
                      - moment_color
                      - moment_primary_story_color
                      - moment_primary_story_name
                      - moment_scheduled_at
                      - post_moment_color
                      - post_moment_name
                      - post_scheduled_at
                      - post_service_color
                      - post_service_system_name
                      - story_color
                      - story_scheduled_end_at
                      - story_scheduled_start_at
                      - user_emails
                      - user_job_title
                      properties:
                        type:
                          type: string
                          enum:
                          - asset_reference
                          - board
                          - moment
                          - post
                          - story
                          - user
                        brand_ids:
                          type: array
                          description: 'NOTE: Records of type "post" or "asset_reference" with a document_version of 1 will serve brand_ids as a single integer.'
                          items:
                            type: integer
                        display_name:
                          type: string
                        document_version:
                          type: integer
                        id:
                          type: integer
                        index_updated_at:
                          type: string
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        is_private:
                          type: boolean
                        is_visible:
                          type: boolean
                        navigation_path:
                          type: string
                        preview_url:
                          type:
                          - string
                          - 'null'
                        asset_reference_uuid:
                          type:
                          - string
                          - 'null'
                        asset_reference_asset_type:
                          type:
                          - string
                          - 'null'
                        asset_reference_created_at:
                          type:
                          - string
                          - 'null'
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        asset_reference_full_url:
                          type:
                          - string
                          - 'null'
                        asset_reference_user_name:
                          type:
                          - string
                          - 'null'
                        board_created_at:
                          type:
                          - string
                          - 'null'
                        board_created_by:
                          type:
                          - string
                          - 'null'
                        moment_color:
                          type:
                          - string
                          - 'null'
                        moment_primary_story_color:
                          type:
                          - string
                          - 'null'
                        moment_primary_story_name:
                          type:
                          - string
                          - 'null'
                        moment_scheduled_at:
                          type:
                          - string
                          - 'null'
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        post_moment_color:
                          type:
                          - string
                          - 'null'
                        post_moment_name:
                          type:
                          - string
                          - 'null'
                        post_scheduled_at:
                          type:
                          - string
                          - 'null'
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        post_service_color:
                          type:
                          - string
                          - 'null'
                        post_service_system_name:
                          type:
                          - string
                          - 'null'
                        story_color:
                          type:
                          - string
                          - 'null'
                        story_scheduled_end_at:
                          type:
                          - string
                          - 'null'
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        story_scheduled_start_at:
                          type:
                          - string
                          - 'null'
                          description: An ISO8601 date-time. Formatted as an 'Internet Date/Time' (RFC 3339).
                          format: date-time
                        user_emails:
                          type:
                          - array
                          - 'null'
                          items:
                            type: string
                        user_job_title:
                          type:
                          - string
                          - 'null'
        '404':
          description: No results found.
          content:
            application/json:
              x-not-json-api: true
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with the authorization code grant flow. You can find more detailed authentication instructions in the [Authentication Strategies](/api/documentation#section/Authentication-Strategies/OAuth-2.0) section.
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/auth
          tokenUrl: /oauth2/token
          scopes:
            offline_access: Include this scope if you wish to receive a refresh token
    api_key:
      type: apiKey
      description: (Deprecated) This API also supports authentication via an API or session token set in the request headers.
      in: header
      name: Session-Token
x-tagGroups:
- name: JSON:API
  tags:
  - Accounts
  - Activities
  - Annotations
  - Asset Reference Options
  - Asset Reference Usage Rights Options
  - Asset References
  - Assets
  - Brand Settings
  - Brands
  - Checkpoints
  - Content
  - Delivery Records
  - Label Sets
  - Labels
  - Messages
  - Moments
  - Phase Items
  - Placements
  - Post Types
  - Privacy
  - Reactions
  - Rich Texts
  - Services
  - Stamps
  - Stories
  - Url Uploads
  - User Domain Views
  - Users
  - Workflows
- name: Other
  tags:
  - Budgets
  - URL Previews
  - Search
  - Stories V1
- name: ⚠️  Unstable
  tags: []
- name: Additional Resources
  tags:
  - secondary_resources
